spring:
  application:
    name: The-Film-Roulette

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    

jwt:
  secret: "ZjFsbnIwMWwxM3R0M0xvbmcyMDI0aGFzaGRmZGdoanNma2xhZGZqa2FzZGZqa3NkanM="

tmdb:
  api:
    key: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5OGM3Y2NmN2MxMmNhYzI4ZTMzYzFiNTA0ZTk1OGU4NSIsIm5iZiI6MTczNzMwNjkwNS43MDg5OTk5LCJzdWIiOiI2NzhkMzMxOWU0NTY2Mzk5YTI2ZGZiNDMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.6wAeCSMBXlWYzTuqPTpmNBNf-uL4bAOBZFB8Y0pQt9g"
